inspire/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
app_name = 'inspire'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('works.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schema_view = get_schema_view(
    openapi.Info(
        title="Inspire Companies API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="easydush@gmail.com"),
        license=openapi.License(name="ITIS License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns += [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]
urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

import main
from . import views
from .views import CompanyViewSet, ResetPasswordView, ResetPasswordRequestView, MessageSentView

app_name = 'main'

router = DefaultRouter()
router.register(r'companies', CompanyViewSet, basename='company')

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileChangeView.as_view(), name='profile_edit'),
    path('logout/', views.logout_view, name='logout'),
    path('about/', views.about, name='about'),
    path('api/', include(router.urls)),
    path('reset/', ResetPasswordRequestView.as_view(), name='reset_request'),
    path('reset-password/<username>/<token>', ResetPasswordView.as_view(), name='reset'),
    path('reset-message/', MessageSentView.as_view(), name='reset_redirect_message'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler500 = 'main.views.error_500'

works/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'works'
urlpatterns = [
    path('photo/', views.PhotoListView.as_view(), name='photo-list'),
    path('photo/<int:pk>/', views.PhotoDetailView.as_view(), name='photo-detail'),
    path('photo/create/', views.PhotoCreateView.as_view(), name='photo-create'),
    path('photo/<int:pk>/update/', views.PhotoUpdateView.as_view(), name='photo-update'),
    path('photo/<int:pk>/delete/', views.PhotoDelete.as_view(), name='photo-delete'),
    path('work/stylist', views.StylistWorksView.as_view(), name='stylistwork-list'),
    path('work/visagist', views.MakeUpWorksView.as_view(), name='makeupwork-list'),
    path('work/photographer', views.PhotographerWorksView.as_view(), name='photographerwork-list'),
    path('work/model', views.ModelWorksView.as_view(), name='modelwork-list'),
    path('work/stylist/create', views.AddStylistWorkView.as_view(), name='stylistwork-add'),
    path('work/visagist/create', views.AddVisagistWorkView.as_view(), name='makeupwork-add'),
    path('work/photographer/create', views.AddPhotographerWorkView.as_view(), name='photographerwork-add'),
    path('work/model/create', views.AddModelWorkView.as_view(), name='modelwork-add'),
]
# for items
urlpatterns += [
    path('item/', views.ItemListView.as_view(), name='item-list'),
    path('item/<int:pk>/', views.ItemDetailView.as_view(), name='item-detail'),
    path('item/create/', views.ItemCreateView.as_view(), name='item-create'),
    path('item/<int:pk>/update/', views.ItemUpdateView.as_view(), name='item-update'),
    path('item/<int:pk>/delete/', views.ItemDelete.as_view(), name='item-delete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% block title %}
    Inspire
{% endblock %}
{% load static %}
{% block content %}
    <div class="container" style="width: 50%">
    <h2>We are cool!</h2>
    <table border="1">
        <tr>
            <td>Stylist works</td>
            <td>{{ stw }}</td>
        </tr>
        <tr>
            <td>Photographer works</td>
            <td>{{ phw }}</td>
        </tr>
        <tr>
            <td>Model works</td>
            <td>{{ mdw }}</td>
        </tr>
        <tr>
            <td>Make up artist works</td>
            <td>{{ mkw }}</td>
        </tr>
    </table>
     <table border="1">
        <tr>
            <td>Max price</td>
            <td>{{ max_p }}</td>
        </tr>
        <tr>
            <td>Min price</td>
            <td>{{ min_p }}</td>
        </tr>
        <tr>
            <td>Items count</td>
            <td>{{ items }}</td>
        </tr>
         <tr>
            <td>Items which price is greater than id</td>
            <td>{{ gtid }}</td>
        </tr>
         <tr>
            <td>It is ITIS, isn't it?</td>
            <td>{{ itis }}</td>
        </tr>

    </table>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}</title>
    {% block add_style %} {% endblock %}

    <link href="{% static 'main/css/style.css' %}" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/2921dfc6f5.js"></script>
</head>
<body>
{% include 'navbar.html' %}
{% block content %}

{% endblock %}

{% include 'footer.html' %}
{% block js %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
{% endblock %}

</body>
</html>

templates/footer.html
<footer class="page-footer font-small  darken-3">

    <!-- Footer -->
    <div class="container">
        <hr>
        <div class="text-center center-block">
            <p class="txt-railway">Follow us</p>
            <a href="https://vk.com/izidamadridista"><i id="social-vk"
                                                            class="fa fa-vk fa-3x social"></i></a>
            <a href="https://instagram.com/easydush"><i id="social-in" class="fa fa-instagram fa-3x social"></i></a>
            <a href="https://github.com/easydush/inspire"><i id="social-git" class="fa fa-github fa-3x social"></i></a>
            <a href="mailto:easydush@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
        </div>
    </div>
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="https://mdbootstrap.com/"> easydush</a>
    </div>

</footer>

templates/index.html
{% extends 'base.html' %}
{% block title %}
    Inspire
{% endblock %}
{% load static %}
{% block content %}
    <div id="slides" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#slides" data-slide-to="0" class="active"></li>
            <li data-target="#slides" data-slide-to="1"></li>
            <li data-target="#slides" data-slide-to="2"></li>
            <li data-target="#slides" data-slide-to="3"></li>

            <li data-target="#slides" data-slide-to="4"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'main/images/model.png' %}" class="img-fluid d-block w-100" alt="blogger1">
                <div class="carousel-caption display-1">
                    <b>Look at the model...</b>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'main/images/photographer.png' %}" class="img-fluid d-block w-100" alt="blogger2">
                <div class="carousel-caption display-1">
                    <b>And a good photographer...</b>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'main/images/stylist.png' %}" class="img-fluid d-block w-100"
                     alt="Share your looks with your friends and become a superstar">
                <div class="carousel-caption display-1">
                    <b>Remember about stylist...</b>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'main/images/visagist.png' %}" class="img-fluid d-block w-100"
                     alt="Share your looks with your friends and become a superstar">
                <div class="carousel-caption display-1">
                    <b>Some visagist's magic...</b>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'main/images/photos.png' %}" class="img-fluid d-block w-100"
                     alt="Share your looks with your friends and become a superstar">
                <div class="carousel-caption display-1">
                    {% comment %}<h1>Follow your favourite blogger</h1>{% endcomment %}
                    <b>And your photo is ready!</b>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#slides" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#slides" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    {% comment %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
{% endcomment %}

{% endblock %}

templates/navbar.html
{% load static %}
<div class="d-flex flex-column flex-md-row align-items-center p-2 px-md-3 mb-2 bg-white border-bottom shadow-sm">
    <img src="{% static 'main/images/inspire.png' %}" class="img-fluid" alt="hanger">
    <h2 class="my-0 mr-md-auto font-weight-normal">inspire</h2>
    <a class="btn btn-outline-primary m-1" href="{% url 'main:index' %}">Home <span class="sr-only">(current)</span></a>
    <a class="btn btn-outline-info m-1" href="{% url 'main:about' %}">About us <span
            class="sr-only">(current)</span></a>
    <a class="btn btn-outline-dark m-1" href="{% url 'works:photo-list' %}">Photos <span
            class="sr-only">(current)</span></a>
    <a class="btn btn-outline-warning m-1" href="{% url 'works:item-list' %}">Items <span
            class="sr-only">(current)</span></a>

    <nav class="my-2 my-md-0 mr-md-3 ">


        {% if user.is_authenticated %}
            <a class="btn btn-outline-dark m-1" href="{% url 'works:photographerwork-list' %}">Photographers <span class="sr-only">(current)</span></a>
             <a class="btn btn-outline-primary m-1" href="{% url 'works:modelwork-list' %}">Models <span class="sr-only">(current)</span></a>
             <a class="btn btn-outline-info m-1" href="{% url 'works:stylistwork-list' %}">Stylists <span class="sr-only">(current)</span></a>
             <a class="btn btn-outline-secondary m-1" href="{% url 'works:makeupwork-list' %}">Make Up Artists<span class="sr-only">(current)</span></a>
            <a class="btn btn-outline-success m-1" href="{% url 'main:profile' %}">Hello, {{ user.get_username }}</a>
            <a class="btn btn-outline-danger" href="{% url 'main:logout' %}">Log out</a>
        {% else %}
            <a class="btn btn-outline-success m-1" href="{% url 'main:login' %}">Sign in</a>
            <a class="btn btn-outline-primary" href="{% url 'main:register' %}">Sign up</a>
        {% endif %}


    </nav>
</div>